### ISSUE TITLE
missing files

### ISSUE THREAD

**Issue by mastawell** [BitClubDev/ClubCoin#10]
qmake does not work:
WARNING: Failure to find: src/version.cpp
WARNING: Failure to find: src/qt/forms/rpcconsole.ui

make error:
src/version.cpp:46:9: error: expected ‘)’ before ‘DO_STRINGIZE’
     "v" DO_STRINGIZE(maj) "." DO_STRINGIZE(min) "." DO_STRINGIZE(rev) "." DO_STRINGIZE(build) "-g" commit
         ^
src/version.cpp:53:28: note: in expansion of macro ‘BUILD_DESC_FROM_COMMIT’
 #        define BUILD_DESC BUILD_DESC_FROM_COMMIT(CLIENT_VERSION_MAJOR, CLIENT_VERSION_MINOR, CLIENT_VERSION_REVISION, CLIENT_VERSION_BUILD, GIT_COMMIT_ID)
                            ^
src/version.cpp:67:32: note: in expansion of macro ‘BUILD_DESC’
 const std::string CLIENT_BUILD(BUILD_DESC CLIENT_VERSION_SUFFIX);
                                ^
Makefile:1543: recipe for target 'build/version.o' failed

**Comment by sinetek** [comment]
Hi there, thanks for the bug report. We do not use the Qt project file directly, please configure using autotools.

sh autogen.sh
./configure etc etc

**Comment by sinetek** [comment]
I need to rewrite the documentation for ClubCoin, that's on the radar. In particular, Windows and OS X builds are done on Linux now, though it should work on OS X given enough `brew install`.

**Comment by mastawell** [comment]
thanks. well I am trying to get the thing running on my Raspberry Pi and its giving me some pain.

**Comment by sinetek** [comment]
Ah, I'm sorry about that, if you have more specific questions I can help.
Let me load up raspbian and I'll give you a little guide. Or what distro are you using?

**Comment by mastawell** [comment]
yes I am using raspian. actuall 
actually I had to apt-get libprotobuf-dev and libevent-dev, used configure --with-incompatible-bdb
now make is taking a while ... still running

**Comment by sinetek** [comment]
cool ^^. You may run into memory issues, as the Pi doesn't have a lot of memory. In that case make a swapfile and off you go.

for official builds we use db 4.8.30  but when building for yourself --with-incompatible-bdb is just fine.

**Comment by mastawell** [comment]
well thats exatly where i ended up ... memory issues ... i should have moved the swap to an USB stick before

**Comment by mastawell** [comment]
thanks for your advise

**Comment by sinetek** [comment]
no problem. closing now, reopen if problem.
